name: Nexus-Miner
on:
  workflow_dispatch:
jobs:
  Nexus-Job:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Download and Install Nexus
        run: |
          curl https://cli.nexus.xyz/install.sh | sh
      - name: Run Nexus Miner
        run: |
          ./.nexus/bin/nexus-cli start --max-threads 2 &
      - name: Keep Alive Loop
        run: |
          while true; do
            echo "[$(date)] Nexus is running..."
            sleep 300
          done

        
